# Generated by Django 3.2.6 on 2021-08-19 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_booster_regions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.IntegerField(choices=[('EUNE', 'EUNE'), ('EUW', 'EUW'), ('NA', 'NA'), ('RU', 'RU'), ('TR', 'TR')])),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('flash_key', models.CharField(choices=[('D', 'D'), ('F', 'F')], max_length=1)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('OPEN', 'OPEN'), ('DONE', 'DONE')], max_length=20)),
                ('booster', models.ForeignKey(null=True, on_delete=models.SET('deleted'), to='accounts.booster')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WinBoosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(choices=[('SOLOQ', 'SOLOQ'), ('FLEXQ', 'FLEXQ')], max_length=10)),
                ('start_rank', models.CharField(choices=[('I', 'Iron'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold'), ('P', 'Platiuim'), ('D', 'Diamond'), ('M', 'Master')], max_length=10)),
                ('start_div', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])),
                ('start_lp', models.IntegerField()),
                ('gain_lp', models.IntegerField()),
                ('win_expected', models.IntegerField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lolboost.order')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementBoosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(choices=[('SOLOQ', 'SOLOQ'), ('FLEXQ', 'FLEXQ')], max_length=10)),
                ('previous_rank', models.CharField(choices=[('I', 'Iron'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold'), ('P', 'Platiuim'), ('D', 'Diamond'), ('M', 'Master')], max_length=10)),
                ('previous_div', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])),
                ('match_numbers', models.IntegerField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lolboost.order')),
            ],
        ),
        migrations.CreateModel(
            name='DivisionBoosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(choices=[('SOLOQ', 'SOLOQ'), ('FLEXQ', 'FLEXQ')], max_length=10)),
                ('start_rank', models.CharField(choices=[('I', 'Iron'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold'), ('P', 'Platiuim'), ('D', 'Diamond'), ('M', 'Master')], max_length=10)),
                ('start_div', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])),
                ('start_lp', models.IntegerField()),
                ('gain_lp', models.IntegerField()),
                ('end_rank', models.CharField(choices=[('I', 'Iron'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold'), ('P', 'Platiuim'), ('D', 'Diamond'), ('M', 'Master')], max_length=10)),
                ('end_div', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lolboost.order')),
            ],
        ),
    ]
