# Generated by Django 3.2.6 on 2021-08-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolboost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='server',
            field=models.CharField(choices=[('EUNE', 'EUNE'), ('EUW', 'EUW'), ('NA', 'NA'), ('RU', 'RU'), ('TR', 'TR')], max_length=10),
        ),
    ]
