# Generated by Django 3.2.6 on 2021-08-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolboost', '0002_alter_order_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
    ]
