# Generated by Django 3.2.6 on 2021-08-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolboost', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flash_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='server',
        ),
        migrations.AddField(
            model_name='divisionboosting',
            name='flash_key',
            field=models.CharField(choices=[('D', 'D'), ('F', 'F')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='divisionboosting',
            name='server',
            field=models.CharField(choices=[('EUNE', 'EUNE'), ('EUW', 'EUW'), ('NA', 'NA'), ('RU', 'RU'), ('TR', 'TR')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='placementboosting',
            name='flash_key',
            field=models.CharField(choices=[('D', 'D'), ('F', 'F')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='placementboosting',
            name='server',
            field=models.CharField(choices=[('EUNE', 'EUNE'), ('EUW', 'EUW'), ('NA', 'NA'), ('RU', 'RU'), ('TR', 'TR')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='winboosting',
            name='flash_key',
            field=models.CharField(choices=[('D', 'D'), ('F', 'F')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='winboosting',
            name='server',
            field=models.CharField(choices=[('EUNE', 'EUNE'), ('EUW', 'EUW'), ('NA', 'NA'), ('RU', 'RU'), ('TR', 'TR')], max_length=10, null=True),
        ),
    ]
