# Generated by Django 3.2.6 on 2021-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolboost', '0004_auto_20210819_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionboosting',
            name='start_div',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='winboosting',
            name='start_div',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10),
        ),
    ]
