# Generated by Django 3.2.6 on 2021-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_booster_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='orders_done',
            field=models.IntegerField(verbose_name='orders done'),
        ),
    ]
