# Generated by Django 3.2.6 on 2021-08-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210819_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booster',
            name='orders_done',
            field=models.IntegerField(),
        ),
    ]
